# -*- coding: utf-8 -*-
"""agents-in-langchain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j3UadJNol0GswNjNVhkocjKS8gxRbGyH
"""

# Clean install to resolve dependency conflicts by allowing pip to choose latest compatible versions
!pip install langchain-community langchain-core langchain-google-genai duckduckgo-search langchainhub requests

# 2. Setup Environment and Suppress Warnings
import os
import warnings
import datetime

# API Keys
os.environ["GOOGLE_API_KEY"] = "YOUR_GOOGLE_API_KEY" # Please replace 'YOUR_GOOGLE_API_KEY' with your actual key
WEATHER_API_KEY = "Weather_API_KEY" # Set WeatherAPI.com key

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.tools import tool
import requests

from langchain_community.tools import DuckDuckGoSearchRun

# 4. Define Tools
search_tool = DuckDuckGoSearchRun()

search_tool.invoke("What is the capital of India?")

@tool
def get_weather_data(city: str) -> str:
    """
    Fetch current weather for a city using WeatherAPI.com.
    Input should be a city name (e.g., 'Hyderabad').
    """
    # Use http for better compatibility on free tiers if https fails
    url = f"http://api.weatherapi.com/v1/current.json?key={WEATHER_API_KEY}&q={city}&aqi=no"

    try:
        # Added a 10-second timeout to prevent the agent from hanging forever
        response = requests.get(url, timeout=10)

        # Check if the server actually returned a 200 OK
        response.raise_for_status()

        data = response.json()

        if "current" in data:
            temp = data['current']['temp_c']
            condition = data['current']['condition']['text']
            return (f"The current weather in {city} is {condition} "
                    f"with a temperature of {temp}°C.")

        return f"WeatherAPI returned success but no data for {city}."

    except requests.exceptions.Timeout:
        return f"Error: The weather service is currently timing out. Please try again in a minute."
    except requests.exceptions.HTTPError as http_err:
        return f"HTTP error occurred: {http_err}"
    except Exception as e:
        return f"An unexpected error occurred: {e}"

get_weather_data.invoke({'city':'Delhi'})



# 4. LLM model
from langchain_google_genai import HarmCategory, HarmBlockThreshold

llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    temperature=0,
    safety_settings={
        HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: HarmBlockThreshold.BLOCK_NONE,
    }
)

ai_result = llm.invoke("What is the capital of India?")
print(ai_result)

from langchain.agents import create_react_agent, AgentExecutor
from langchain import hub

# Pull the standard ReAct prompt
prompt = hub.pull("hwchase17/react")

# Define tool list
tools = [search_tool, get_weather_data]

# Create the ReAct agent

agent = create_react_agent(
    llm=llm,
    tools=tools,
    prompt=prompt
)

# 5. Execute
agent_executor = AgentExecutor(
    agent=agent,
    tools=tools,
    verbose=True,
    handle_parsing_errors=True # Crucial for stability
)

response = agent_executor.invoke({"input": "the capital of India is Delhi , find it's current weather condition of capital of india"})
print(response)

print(response.get('output'))