# -*- coding: utf-8 -*-
"""agents-in-langchain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j3UadJNol0GswNjNVhkocjKS8gxRbGyH
"""

!pip install -q langchain==0.1.16 langchain-openai langchain-community duckduckgo-search langchainhub requests
!pip install -q -U ddgs

import os

os.environ["OPENAI_API_KEY"] = "YOUR_OPENAI_KEY"

from langchain_openai import ChatOpenAI
from langchain_core.tools import tool
from langchain_community.tools import DuckDuckGoSearchRun
from langchain.agents import AgentExecutor
from langchain.agents.react.agent import create_react_agent
from langchain import hub
import requests

search_tool = DuckDuckGoSearchRun()

@tool
def get_weather_data(city: str) -> str:
    """
    Fetch current weather for a city
    """
    url = f"https://api.weatherstack.com/current?access_key=YOUR_WEATHERSTACK_KEY&query={city}"

    response = requests.get(url)

    return str(response.json())

llm = ChatOpenAI()

prompt = hub.pull("hwchase17/react")

agent = create_react_agent(
    llm=llm,
    tools=[search_tool, get_weather_data],
    prompt=prompt
)

agent_executor = AgentExecutor(
    agent=agent,
    tools=[search_tool, get_weather_data],
    verbose=True
)

response = agent_executor.invoke(
    {"input": "Find the capital of Madhya Pradesh and tell the current weather there"}
)

print(response["output"])