# -*- coding: utf-8 -*-
"""tool-calling-in-langchain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PD68EY0E-Ik0SLAEexNvoY3Wf_O3a17X

#tool binding
"""

import os
os.environ["OPENAI_API_KEY"] = "Paste API KEY Here"

!pip install -q langchain-openai langchain-core requests

from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage
from langchain_core.tools import tool

# tool create
@tool
def multiply(a: int, b: int) -> int:
    """ Given 2 numbers a and b this returns their product """
    return a * b

print(multiply.invoke({"a": 3, "b": 4}))

#tool binding

llm = ChatOpenAI()
tools = [multiply]
llm_with_tools = llm.bind(tools=tools)

"""Tool calling"""

result = llm_with_tools.invoke("What is 3 times 4?")

result.tool_calls

input = result.tool_calls[0]['args']

"""Tool Execution"""

multiply.invoke(input)

"""tool massage"""

tool_message = multiply.invoke(result.tool_calls[0])

"""final full query content"""

query = HumanMessage('can you multiply 3 with 1000')

message = [query]

message

result = llm_with_tools.invoke(message)

message.append(result)

tool_message = multiply.invoke(result.tool_calls[0])

message.append(tool_message)

llm_with_tools.invoke(message).content