# -*- coding: utf-8 -*-
"""tools-Using-langchain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gjp3fnoYgUmQpD456vYcaDsqXxLBb_Cp
"""

!pip install langchain-core langchain-community pydantic duckduckgo-search

"""BUILT-in Tool- DUckDuckGo Search"""

from langchain_community.tools import DuckDuckGoSearchRun
search_tool = DuckDuckGoSearchRun()
results = search_tool.invoke('top news in bihat today ')
print(results)

"""BUILT-in Tool- Shell Tool"""

!pip install langchain-experimental

from langchain_community.tools import ShellTool
shell_tool = ShellTool()
results = shell_tool.invoke('ls')
print(results)

"""# Custom Tools"""

from langchain_core.tools import tool

#step 1 - crearte a function
def multiply(a,b):
  """ multipy two numbers """ ##[important- Add Doc string] it help llm to understand what this tool does
  return a*b

#step 2- add type hints
def multiply(a:int, b:int)->int:
  """multiply two numbers"""
  return a*b

#step 3 - add tool decorator
@tool
def multiply(a:int, b:int)->int:
  """multiply two numbers"""
  return a*b

results = multiply.invoke({"a":3, "b":4})

print(results)

"""atributes of tools"""

print(multiply.name)
print(multiply.description)
print(multiply.args)

"""llm what see the tools in like json schema"""

print(multiply.args_schema.model_json_schema())

"""with help of structure Pydantic"""

from langchain_core.tools import StructuredTool
from pydantic import BaseModel, Field

class MultiplyInput(BaseModel):
  a:int = Field(required=True, description="the first number to add")
  b:int = Field(required=True, description="the second number to add")

def multiply_func(a:int, b:int) ->int:
  return a*b

multiply_tool = StructuredTool.from_function(
    func=multiply_func,
    name="multiply",
    description="multiply two numbers",
    args_schema=MultiplyInput
)

results = multiply_tool.invoke({'a':3,'b':4})
print(results)